// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqihfqvmcavaxzcvpnwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxaWhmcXZtY2F2YXh6Y3ZwbndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDczOTcsImV4cCI6MjA3MjcyMzM5N30.Fzd6XPqXKtjNvFxUgetiD32fMTagbT4bT6991vwAd78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});